name: Build Unity client

on:
  workflow_dispatch:

jobs:
    build-unity:
        runs-on: [self-hosted, Linux]
        steps:
            - name: Checkout
              uses: actions/checkout@v4
        
            - name: Cache Library folder
              uses: actions/cache@v3
              with:
                path: Library
                key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
                restore-keys: |
                  Library-

            - name: Run tests
              uses: game-ci/unity-test-runner@v4
              env:
                UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                githubToken: ${{ secrets.GITHUB_TOKEN }}

            - name: Build project
              uses: game-ci/unity-builder@v4
              env:
                UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}                
              with:
                allowDirtyBuild: true
                targetPlatform: StandaloneWindows64
      
            - name: Upload build artifact
              uses: actions/upload-artifact@v3
              with:
                name: Build
                path: build

            - name: Upload to itch.io
              uses: robpc/itchio-upload-action@v1
              with:
                path: build
                project: "bhat-ganesh/unity-hello-world"
                channel: "windows"
                version: ${{ github.run_number }}
                api-key: ${{ secrets.ITCHIO_API_KEY }}