name: Build Unity client

on:
  workflow_dispatch:

jobs:
    build-unity:
        runs-on: [self-hosted, Linux]
        strategy:
            matrix:
              target:
                - platform: StandaloneWindows64
                  channel: windows
                - platform: StandaloneOSX
                  channel: mac
        steps:
            - name: Checkout
              uses: actions/checkout@v4
        
            - name: Cache Library folder
              uses: actions/cache@v3
              with:
                path: Library
                key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
                restore-keys: |
                  Library-

            - name: Run tests
              uses: game-ci/unity-test-runner@v4
              env:
                UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                githubToken: ${{ secrets.GITHUB_TOKEN }}

            - name: Build ${{ matrix.target.channel }} project
              uses: game-ci/unity-builder@v4
              env:
                UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}                
              with:
                allowDirtyBuild: true
                targetPlatform: ${{ matrix.target.platform }}
      
            - name: Upload build artifact
              uses: actions/upload-artifact@v3
              with:
                name: Build
                path: build

            - name: Upload ${{ matrix.target.channel }} build to itch.io
              uses: robpc/itchio-upload-action@v1
              with:
                path: build
                project: "bhat-ganesh/unity-hello-world"
                channel: ${{ matrix.target.channel }}
                version: ${{ github.run_number }}
                api-key: ${{ secrets.ITCHIO_API_KEY }}

            - name: Notify Slack channel
              uses: slackapi/slack-github-action@v1.25.0
              with:
                channel-id: 'C06FXM8PZ5G'
                slack-message: "${{ matrix.target.channel }} build #${{ github.run_number }}: ${{ job.status }}.\n
                                Download logs here https://github.com/${{ github.actor }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}\n
                                Download builds here https://${{ github.actor }}.itch.io/${{ github.event.repository.name }}"
              env:
                SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}