name: Sandbox Workflow

on:
  workflow_dispatch:

jobs:
    sandbox:
        runs-on: [self-hosted, Linux]
        container: node:21
        steps:
            - name: Run
              run: |
                  echo "Hello World"
                  echo "github.workspace = ${{ github.workspace }}"
                  node --version
                  npm --version

            - name: Post to a Slack channel
              id: slack
              uses: slackapi/slack-github-action@v1.25.0
              with:
                # Slack channel id, channel name, or user id to post message.
                # See also: https://api.slack.com/methods/chat.postMessage#channels
                # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
                channel-id: 'C06FXM8PZ5G'
                # For posting a simple plain text message
                slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
              env:
                SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}