name: Sandbox Workflow

on:
  workflow_dispatch:

jobs:
    sandbox:
        runs-on: [self-hosted, Linux]
        # container: node:21
        steps:
            - name: Run
              run: |
                  echo "Hello World"
                  echo "github.workspace = ${{ github.workspace }}"
                  echo "github.event.repository.name = ${{ github.event.repository.name }}"
                  echo "github.actor = ${{ github.actor }}"

            #       node --version
            #       npm --version

            - name: Post to a Slack channel
              uses: slackapi/slack-github-action@v1.25.0
              with:
                channel-id: 'C06FXM8PZ5G'
                slack-message: "GitHub build result: ${{ job.status }}. visit https://${{ github.actor }}.itch.io/${{ github.event.repository.name }}"
              env:
                SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}