name: Sandbox Workflow

on:
  workflow_dispatch:

jobs:
    sandbox:
        runs-on: [self-hosted, Linux]
        # container: node:21
        steps:
            - name: Run
              run: |
                  echo "Hello World"
                  echo "github.workspace = ${{ github.workspace }}"
                  echo "github.event.repository.name = ${{ github.event.repository.name }}"
                  echo "github.actor = ${{ github.actor }}"

            #       node --version
            #       npm --version

            - name: Post to a Slack channel
              uses: slackapi/slack-github-action@v1.25.0
              with:
                channel-id: 'C06FXM8PZ5G'
                slack-messsage: {
                                  "blocks": [
                                    {
                                      "type": "section",
                                      "text": {
                                        "type": "mrkdwn",
                                        "text": "Build ${{ github.run_number }}: *${{ job.status }}*.\n
                Download logs <https://github.com/${{ github.actor }}/${{ github.event.repository.name }}/actions/runs/${{ github.run_id }}|here>\n
                Download builds <https://${{ github.actor }}.itch.io/${{ github.event.repository.name }}|here>"
                                      }
                                    }
                                  ]
                                }
              env:
                SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}