name: Sandbox Workflow

on:
  workflow_dispatch:

jobs:
    sandbox:
        runs-on: [self-hosted, Linux]
        # container: node:21
        steps:
            - name: Run
              run: |
                  echo "Hello World"
                  echo "github.workspace = ${{ github.workspace }}"
                  echo "github.event.repository.name = ${{ github.event.repository.name }}"
                  echo "github.event.org.login = ${{ github.event.org.login }}"
                  echo "github.event.actor.login = ${{ github.event.actor.login }}"

            #       node --version
            #       npm --version

            # - name: Post to a Slack channel
            #   id: slack
            #   uses: slackapi/slack-github-action@v1.25.0
            #   with:
            #     # Slack channel id, channel name, or user id to post message.
            #     # See also: https://api.slack.com/methods/chat.postMessage#channels
            #     # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
            #     channel-id: 'C06FXM8PZ5G'
            #     # For posting a simple plain text message
            #     slack-message: "GitHub build result: ${{ job.status }}"
            #   env:
            #     SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}